version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/frontend/node_modules
      - /app/packages/shared/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080/api}
    depends_on:
      - backend
    networks:
      - dosukebe-ranking-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "8080:8080"
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=mysql://user:password@db:3306/dosukeberanking
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - db
    networks:
      - dosukebe-ranking-network

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dosukeberanking
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dosukebe-ranking-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - dosukebe-ranking-network

volumes:
  db-data:

networks:
  dosukebe-ranking-network:
    driver: bridge